#18 - 상품 주문 기능 추가
f-lab-edu/modu-ui-market pull request #31
Opened 2023-04-24 14:27 UTC by chanwoothecali

2023-04-26 02:33 UTC, ChaYujin requested changes

2023-04-26 02:33 UTC, ChaYujin commented on src/main/java/com/flab/modu/order/controller/OrderDto.java
> +        private Long productId;
주문시 상품 1개만 주문 가능한 건가요~? 여러 개의 상품을 한꺼번에 주문하는 경우에는 어떻게 처리가 되는지 궁금합니다

2023-04-26 02:33 UTC, ChaYujin commented on src/main/java/com/flab/modu/order/domain/entity/Order.java
> +}
EOF 뉴라인이 빠졌습니다!

2023-04-26 02:33 UTC, ChaYujin commented on src/main/java/com/flab/modu/order/domain/entity/OrderProduct.java
> +}
여기도 EOF 빠졌어요

2023-04-26 02:45 UTC, f-lab-michael commented on src/main/java/com/flab/modu/product/service/ProductService.java
> +        checkStockAvailability(product.getStock(), orderAmount);
재고가 하나 남은 상황에서 동시에 두개의 구매 요청이 들어오는경우 어떤 문제가 생길까요?

문제를 해결하기 위해서 어떤 방법을 사용할수있을까요?

2023-04-26 04:04 UTC, chanwoothecali commented on src/main/java/com/flab/modu/order/controller/OrderDto.java
> +        private Long productId;
커머스 도메인에서 '즉시 구매'에 해당하는 기능이라고 보시면 됩니다. 추후 장바구니를 통한 구매를 추가할 예정입니다.

2023-04-26 04:04 UTC, chanwoothecali commented on src/main/java/com/flab/modu/order/domain/entity/Order.java
> +}
수정하겠습니다!

2023-04-26 06:06 UTC, chanwoothecali commented on src/main/java/com/flab/modu/product/service/ProductService.java
> +        checkStockAvailability(product.getStock(), orderAmount);
데이터를 읽는 과정에서 상품 재고가 있는 것으로 데이터를 반환 받아, 두 개의 주문 모두 성공하는 문제가 생길 수 있습니다.

해당 문제를 해결하기 위해서는 다음과 같은 방법을 사용할 수 있습니다.
1. 비관적 락
    - JPA `@Lock(value = LockModeType.PESSIMISTIC_WRITE)`을 통해 레코드에 락을 걸어 동시성 문제를 해결하는 방법입니다.
2. 낙관적 락
    - JPA `@Version` 어노테이션을 통해 나중에 이루어지는 주문은 update 쿼리를 실패하게 만드는 방법입니다.
3. 분산 락
    - ZooKeeper, Redis 등 분산 락을 이용해 리소스가 사용중인지 체크하여 해결하는 방식입니다.

2023-04-26 18:31 UTC, f-lab-michael commented on src/main/java/com/flab/modu/product/service/ProductService.java
> +        checkStockAvailability(product.getStock(), orderAmount);
1 또는 2를 통해서 구현을 해보시면 좋을것 같습니다.

2023-05-07 11:07 UTC, chanwoothecali commented on src/main/java/com/flab/modu/product/service/ProductService.java
> +        checkStockAvailability(product.getStock(), orderAmount);
1. 비관적 락
    - 장점: 데이터 무결성을 보장하는 수준이 높습니다. 충돌이 일어났을 때 해당 트랜잭션을 롤백하는 작업만 하면 됩니다.
    - 단점: 데이터에 락을 거는 방식이라 동시 요청시 성능이 떨어집니다. 동시에 자원을 요구하는 경우 데드락이 발생할 수 있습니다.
2. 낙관적 락
    - 장점: 어플리케이션 레벨에서 트랜잭션을 보장하기 때문에 비관적 락에 비해 성능이 좋습니다.
    - 단점: 충돌이 일어났을 경우 롤백 처리에 대한 로직 구현이 필요하며, 롤백 로직에 따라 성능이 더 안좋아질 수 있습니다.

낙관적 락은 비관적 락에 비해 동시 요청에 대한 성능이 높지만, 충돌이 잦은 로직에 적용할 경우 오히려 성능이 떨어질 수 있습니다.

결론적으로 낙관적 락은 비교적 충돌이 적은 로직 혹은 롤백 처리가 간단한 경우에 적용하는 것이 맞다고 생각합니다.
저희 주문 로직의 경우 충돌이 적을 것이라 예상되며, 롤백 처리에 대한 로직이 필요하지 않아 낙관적 락으로 적용하는 방향으로 결정했습니다.

2023-06-12 05:18 UTC, ChaYujin commented on src/test/java/com/flab/modu/order/service/OrderServiceConcurrencyTest.java
> +                orderCallService.callOrder(orderRequest, EMAIL);
Jenkins에서 테스트 중에 실패했는데, 테스트 성공할 수 있게 확인 부탁드려요!

2023-06-12 09:09 UTC, chanwoothecali commented on src/test/java/com/flab/modu/order/service/OrderServiceConcurrencyTest.java
> +                orderCallService.callOrder(orderRequest, EMAIL);
> Jenkins에서 테스트 중에 실패했는데, 테스트 성공할 수 있게 확인 부탁드려요!

수정하였습니다!

2023-06-19 07:24 UTC, ChaYujin commented on src/main/java/com/flab/modu/order/domain/common/OrderStatus.java
> +    DELIVERED,
SHIPPED와 DELIVERED 의 의미가 비슷해보입니다! 두개 각각 어떤 의미인지 설명해주실 수 있으실까요~?
배송중, 배송완료를 의미하는 것이라면 다른 단어로 표현하면 좋을 것 같습니다!

2023-06-19 07:24 UTC, ChaYujin commented on src/main/java/com/flab/modu/global/exception/GlobalExceptionHandler.java
> +        return new ResponseStatusException(HttpStatus.BAD_REQUEST, exception.getMessage());
InsufficientStockException을 만들 때, ResponseStatusException을 상속받아서 처리할 수도 있지않을까요~?
그렇게 처리하면 ExceptionHandler에 따로 추가할 필요없이 Exception을 처리할 수 있어서 유연한 코드가 될 것 같습니다.
만약 ExceptionHandler에 추가해야만 하는 이유가 있다면 알려주세요!

2023-06-19 07:24 UTC, ChaYujin commented on src/main/java/com/flab/modu/order/service/OrderCallService.java
> +            throw new OrderFailureException();
OrderFailureException이 발생했을 때, 에러를 어디서 받아서 처리되고 어떤 응답값을 보내게 되는지 확인 부탁드립니다!
RuntimeException을 상속받아서 만들어진 Exception인데, GlobalExceptionHandler에서도 처리하는 부분이 안보이는 것 같아서 말씀드립니당

2023-06-19 07:24 UTC, ChaYujin commented on src/main/java/com/flab/modu/product/exception/NotExistProductException.java
> +public class NotExistProductException extends RuntimeException {
이 NotExistProductException도 OrderFailureException과 마찬가지로 이 Exception이 발생했을 때, 어디서 처리하는지 확인 부탁드립니다!

2023-06-20 10:29 UTC, chanwoothecali commented on src/main/java/com/flab/modu/order/domain/common/OrderStatus.java
> +    DELIVERED,
SHIPPED에 물류 출하라는 뜻이 있어서 배송 시작을 의미하는 단어로 사용했습니다!
좀 더 명확하게 START_SHIPPING로 수정하겠습니다.

2023-07-04 10:32 UTC, chanwoothecali commented on src/main/java/com/flab/modu/global/exception/GlobalExceptionHandler.java
> +        return new ResponseStatusException(HttpStatus.BAD_REQUEST, exception.getMessage());
생각해보지 못한 부분이네요!
그렇다면 모든 Exception이 ResponseStatusException을 상속받도록 구현하고, 내부에 HttpStatus값을 각자 알맞게 설정해두면 굳이 모든 Exception을 Handler에 추가하지 않아도 될 것 같습니다.
해당 부분은 이슈를 하나 따고 작업을 해봐야겠네요.

2023-07-04 10:44 UTC, chanwoothecali commented on src/main/java/com/flab/modu/order/service/OrderCallService.java
> +            throw new OrderFailureException();
GlobalExcpetionHandler에 OrderFailureException 검증하는 부분 추가하여 푸쉬했습니다.

2023-07-04 10:46 UTC, chanwoothecali commented on src/main/java/com/flab/modu/product/exception/NotExistProductException.java
> +public class NotExistProductException extends RuntimeException {
해당 Exception도 Handler에 추가하였습니다!

2023-07-05 02:37 UTC, ChaYujin approved these changes
변경내용들 모두 확인했습니다. 👍

2023-07-05 02:40 UTC, merged